---
title: "Quality of Life in the World"
author: "Eleni Partakki, Arris Moise and Daniela Martinez"
date: "Last updated on Wednesday, December 11, 2019"
output:
  html_document:
    toc: true
    toc_depth: 2
    toc_float: true
    df_print: kable
---


# SECTION NAME

## Subsection name

Write an intro `index.html` page in blog-post style that summarizes your work. It should have

1. One visualization that best summarizes your work.
1. No more than 200 words of text

```{r, echo = FALSE}
#loading libraries

library(ggplot2)
library(lubridate)
library(tidyr)
library(readr)
library(mapview)
library(tidyverse)
library(sf)
library(htmltools)
library(geojsonio)
library(leaflet)
library(USAboundaries)
library(maps)
library(editData)
library(sp)
library(tmaptools)
library(raster)
library(dplyr)
library(mapview)
library(readr)
```


#Daniela's Section!
#Employment
#Linegraph

```{r, echo = FALSE}
#importing data set

X15plus_employment <- read_csv("15plus_employment.csv")

#getting employment of Togo and France

employment_rate <- X15plus_employment %>% 
  filter(country== "Togo" | country== "France") 
   

new_employment_rate <- gather (employment_rate, key= "year", value= "employment_rate", -country) %>% 
 mutate(year= as.numeric(year)) %>% 
  filter(year >= 2008) %>% 
  filter(year <= 2018) %>% 
  mutate(new_year = lubridate::ymd(year, truncated = 2L)) %>% 
  rename(Country = country)



ggplot(data = new_employment_rate, mapping = aes(x =new_year, y = employment_rate, color= Country)) +
  geom_line(size=1) +
  labs(title= "Employment Rate of Togo and France", subtitle = "2008-2018", x= "Year", y= "Employment Rate")+
  scale_color_manual(values = c("blue","Forestgreen"))

```





#DaniGetDinero
#Life-expectancy
#Mapping?


```{r, echo = FALSE}
#importing data set
life_expectancy_years <- read_csv("life_expectancy_years.csv")
#Wrangle the Countries and Years you want
new_life <- life_expectancy_years 
  
TF_life <- gather (new_life, key= "year", value= "life_expectancy", -country) %>% 
 mutate(year= as.numeric(year)) %>% 
   filter(year == 2018) 
#getting Polys in order to map
world_map <-  maps::map("world", plot = FALSE, fill = TRUE)
world_sf <- world_map %>% 
  sf::st_as_sf(crs = 4326)
world_sf <- rename(world_sf, country=ID)
world_sf <- world_sf %>%
  left_join(TF_life,by = "country")
#Actual Mapping Viz
bins <- c(0,10,20,30,50,60,80,100)
pal <- colorBin("PuRd", domain = world_sf$life_expectancy, bins = bins)
labels <- sprintf(
  "<strong>%s</strong><br/>%g years ",
  world_sf$country, world_sf$life_expectancy
) %>% lapply(htmltools::HTML)
leaflet(world_sf) %>%
  addProviderTiles("MapBox", options = providerTileOptions(
    id = "mapbox.light",
    accessToken = Sys.getenv('MAPBOX_ACCESS_TOKEN'))) %>%
  addPolygons(
  fillColor = ~pal(life_expectancy),
  weight = 2,
  opacity = 1,
  color = "white",
  dashArray = "3",
  fillOpacity = 0.7,
  highlight = highlightOptions(#for when you hover over
    weight = 3,
    color = "grey",
    dashArray = " ",
    fillOpacity = 0.3,
    bringToFront = TRUE),
    label = labels,
    labelOptions = labelOptions(
    style = list("font-weight" = "normal", padding = "3px 8px"),
    textsize = "15px",
    direction = "auto")) %>%
  addLegend(pal = pal, values = ~life_expectancy, opacity = 0.7, title = "Life Expectancy (in years)",
    position = "bottomright")
```






```{r, echo = FALSE}
new_income_for_world <- read_csv("new_income_for_world.csv")


#getting locations of each country
country_locations <- tibble(
  country= c("Azerbaijan", "Bahamas","Bahrain","Bangladesh","Barbados","Belarus","Belgium","Belize","Benin","Bhutan","Bolivia","Bosnia and Herzegovina","Botswana","Brazil","Brunei","Bulgaria","Burkina Faso","Burundi","Cambodia","Cameroon","Canada","Cape Verde","Central African Republic","Chad","Chile","China","Colombia","Comoros","Democratic Republic of the Congo", "Republic of the Congo","Costa Rica","Cote d'Ivoire","Croatia","Cuba","Cyprus","Czech Republic","Denmark","Djibouti","Dominica","Dominican Republic","Ecuador","Egypt","El Salvador","Equatorial Guinea","Eritrea","Estonia","Ethiopia","Fiji","Finland","Gabon","Gambia","Georgia","Germany","Ghana","Greece","Grenada","Guatemala","Guinea","Guinea-Bissau","Guyana", "Haiti","Honduras","Hungray","Iceland","India","Indonesia","Iran","Iraq","Ireland","Israel","Italy","Jamaica","Japan","Jordan","Kazakhstan","Kenya","Kiribati","Kuwait","Kyrgyz Republic","Lao","Lativa","Lebanon","Lesotho","Liberia","Libya","Lithuania","Luxembourg","North Macedonia","Madagascar","Malawi","Malaysia","Maldives","Mali","Malta","Marshall Island","Mauritania","Mauritius","Mexico","Federated States of Micronesia","Moldova","Monaco","Mongolia","Montenegro","Morocco","Mozambique","Myanmar",
"Namibia","Togo","France","Argentina", "Armenia", "Australia","Austria","Nauru","Nepal","Netherlands","New Zealand","Nicaragua","Niger","Nigeria","North Korea","Norway","Oman","Pakistan","Palau","Palestine","Panama","Papua New Guinea","Paraguay","Peru","Philippines", "Poland", "Portugal", "Qatar", "Romania", "Russia", "Rwanda","Samoa", "San Marino","Sao Tome and Principe","Saudi Arabia", "Senegal","Serbia","Seychelles", "Sierra Leone", "Singapore", "Slovak Republic", "Slovenia", "Solomon Islands", "Somalia", "South Africa", "South Korea", "South Sudan","Spain", "Sri Lanka","St. Kitts and Nevis" ,"St.Lucia", "St. Vincent and the Grenadines", "Sudan", "Suriname", "Swaziland", " Syria", "Tajikistan", "Tanzania",
"Thailand","Timor-Leste", "Togo","Tonga", "Trinidad and Tobago", "Tunisia", "Turkey","Turkmenistan", "Tuvalu", "Uganda", "Ukraine", "United Arab Emirates", "United Kingdom", "United States", "Uruguay","Uzbekistan","Vanuatu","Venezuela","Vietnam","Yemen", "Zambia", "Zimbabwe"))
```


```{r, echo = FALSE, cache=TRUE}
#leaflet map creation
country_lat_long <-
  tmaptools::geocode_OSM(country_locations$country)%>%
  as_tibble()
```


```{r, echo = FALSE}
#changing column names
country_lat_long <- country_lat_long %>% 
  mutate(country = query)
new_income <- gather(new_income_for_world, key = "year", value = "income", -country)
new_income <- new_income %>%
  filter(year == "X2019")
USA_map <-  maps::map("world", plot = FALSE, fill = TRUE)

USA_sf <- USA_map %>% 
  sf::st_as_sf(crs = 4326)
USA_sf <- rename(USA_sf, country=ID)
#joining data sets
country_lat_long <- country_lat_long %>%
  left_join(new_income,by="country")
USA_sf <- USA_sf %>%
  left_join(country_lat_long,by = "country")
bins <- c(0,100,500,600,900,1000,10000,50000,100000,500000)
pal <- colorBin("PuBuGn", domain = USA_sf$income, bins = bins)
labels <- sprintf(
  "<strong>%s</strong><br/>%g dollars ",
  USA_sf$country, USA_sf$income
) %>% lapply(htmltools::HTML)
leaflet(USA_sf) %>%
  addProviderTiles("MapBox", options = providerTileOptions(
    id = "mapbox.light",
    accessToken = Sys.getenv('MAPBOX_ACCESS_TOKEN'))) %>%
  addPolygons(
  fillColor = ~pal(income),
  weight = 2,
  opacity = 1,
  color = "white",
  dashArray = "3",
  fillOpacity = 0.7,
  highlight = highlightOptions(#for when you hover over
    weight = 3,
    color = "grey",
    dashArray = " ",
    fillOpacity = 0.3,
    bringToFront = TRUE),
    label = labels,
    labelOptions = labelOptions(
    style = list("font-weight" = "normal", padding = "3px 8px"),
    textsize = "15px",
    direction = "auto")) %>%
  addLegend(pal = pal, values = ~income, opacity = 0.7, title = "Income (in dollars)",
    position = "bottomright") 
```



















```{r, echo = FALSE}
#Sanitation of Togo and France
overall_sanitation <- read_csv("overall_sanitation.csv")
togo_france_sanitation <- overall_sanitation %>%
  filter(country == "Togo" | country == "France" ) 
  
new_sanitation_rate <- gather(togo_france_sanitation, key= "year", value= "sanitation", -country)
#creating the bar plot
togo_france_sanitation <- new_sanitation_rate %>%
  filter(year == "2015"  )
togo_france_sanitation <- togo_france_sanitation %>%
  mutate(new_year = lubridate::ymd(togo_france_sanitation$year, truncated = 2L))
ggplot(data = togo_france_sanitation, mapping = aes(x = country, y = sanitation, fill= country, subtitle = 2008-2018)) + 
  geom_col() + scale_fill_manual(values=c("#0000ff", "#228b22")) + ggtitle("Overall Access to Sanitation Services") +  labs(y="Sanitation", x = "Country")
```













#Eleni
#Death of children under five years of age per 1000 live births

```{r, echo = FALSE}
child_mortality_rate <- read.csv(file = 'child_mortality_per_1000_born.csv')

new_child_mortality <- child_mortality_rate %>% 
  filter(country== "Togo" | country== "France") 

child_mortality <- gather(new_child_mortality, key= "year", value= "mortality_rate", -country) %>% 
  mutate(year = str_replace_all(year, "X", "")) %>% 
  mutate(year= as.numeric(year)) %>% 
  filter(year >= 2008) %>% 
  filter(year <= 2018) %>% 
  mutate(new_year = lubridate::ymd(year, truncated = 2L)) %>% 
  rename(Country = country)
 
ggplot(data = child_mortality, mapping = aes(x = new_year, y = mortality_rate, color = Country)) +
  geom_line(size=1) + 
  scale_color_manual(values = c("blue", "forestgreen"))+
  labs(x="Year", y="Mortality per 1000 live births",subtitle = "2008-2018") +
  ggtitle("Mortality rate of children under five years old in Togo and France")
```


